---
- name: "Rust | {{ ansible_distribution }} | Install rustc cargo"
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop:
    - rustc
    - cargo
