---
- name: Rust | {{ ansible_distribution }} | Install rustc cargo
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop:
    - rustc
    - cargo
