---
- name: Lua | Install Lua
  community.general.pacman:
    name:
      - lua
      - luarocks
      - luajit
  become: true

- name: Lua | Gather installed lua rocks
  ansible.builtin.command: luarocks list
  register: rocks
  changed_when: false
  check_mode: false
