---
- name: Lua | {{ ansible_distribution }}
  community.general.homebrew:
    name:
      - lua
      - luarocks
      - luajit
    state: present

- name: Lua | Gather installed lua rocks
  ansible.builtin.command: luarocks list
  register: rocks
  changed_when: false
  check_mode: false
