---
- name: Lua | {{ ansible_distribution }}
  community.general.homebrew:
    name:
      - lua
      - luarocks
      - luajit
    state: present

- name: Lua | Gather installed lua rocks
  ansible.builtin.command: luarocks list
  register: rocks
  changed_when: false
  check_mode: false

- name: Lua | luarocks install vusted
  ansible.builtin.command:
    cmd: luarocks --lua-version=5.1 install {{ item }}
  loop:
    - vusted
    - luacheck
    - rest.nvim
  changed_when: false
