---
- name: Lua | Update APT cache
  apt:
    update_cache: true
  become: true

- name: Lua | Install Lua
  ansible.builtin.apt:
    name:
      - lua5.1
      - luarocks
      - luajit
  become: true

- name: Lua | Gather installed lua rocks
  ansible.builtin.command: luarocks list
  register: rocks
  changed_when: false
  check_mode: false
