---
- name: Install GitHub CLI tool
  community.general.pacman:
    name: github-cli
    state: present
  become: true

# - name: Authenticate with GitHub using SSH key
#   command: gh auth login --hostname github.com --method ssh
