local servers = {
  "clangd",
  "clang-format",
  "typescript-language-server",
  "lua-language-server",
  "html-lsp",
  "htmx-lsp",
  "css-lsp",
  "tailwindcss-language-server",
  "svelte-language-server",
  "graphql-language-service-cli",
  "emmet-ls",
  "prisma-language-server",
  "pyright",
  "gopls",
  -- "gofumpt",
  -- "golines",
  -- "goimports-reviser",
  "gotests",
  "gotestsum",
  "rust-analyzer",
  "astro-language-server",
  "json-lsp",
  "eslint-lsp",
  "eslint_d",
  "markdownlint",
  "prettier", -- ts/js formatter
  "prettierd", -- ts/js formatter
  "stylua", -- lua formatter
  "selene",
  "ansible-language-server",
  "ansible-lint",
  "golangci-lint",
  "yaml-language-server",
  "yamllint",
  "bash-language-server",
  "cmake-language-server",
  "shellcheck",
  "templ",
  "intelephense",
}

return servers
