---
- name: NVM | Download Latest Version JSON
  ansible.builtin.uri:
    url: https://api.github.com/repos/nvm-sh/nvm/releases/latest
  register: nvm_latest_version_json
  changed_when: false

- name: NVM | Registering NVM Latest Release
  ansible.builtin.set_fact:
    nvm_latest_release: "{{ nvm_latest_version_json.json.tag_name }}"

- name: NVM | Registering NVM Latest Version
  ansible.builtin.set_fact:
    nvm_latest_version: "{{ nvm_latest_release.stdout | default('') }}"

- name: NVM | Show nvm_latest_release debug
  ansible.builtin.debug:
    var: nvm_latest_release

- name: Install nvm
  ansible.builtin.shell: >
    set -o pipefail && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_latest_release }}/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    executable: /bin/bash

- name: NVM | Install latest NodeJS
  block:
    - name: NVM | Get latest STABLE NodeJS version
      ansible.builtin.shell: >
        set -o pipefail
        curl -sL https://nodejs.org/dist/index.json | jq -r '.[] | select(.lts) | .version' | head -n 1
      register: nodejs_latest_version
      changed_when: false

    - name: NVM | Detecting Installed node
      ansible.builtin.command:
        cmd: which node
      changed_when: false
      register: node_cmd
      failed_when: false

    - name: NVM | Register node status installed
      ansible.builtin.set_fact:
        nodejs_is_installed: true
      when: node_cmd.stdout|length > 0

    - name: NVM | Register node status not installed
      ansible.builtin.set_fact:
        nodejs_is_installed: false
      when: node_cmd.stdout|length == 0

    - name: NVM | Check if NodeJS is up to date
      ansible.builtin.command: node --version
      when: nodejs_is_installed
      register: nodejs_up_to_date
      failed_when: false
      changed_when: false

    - name: NVM | Show NodeJS version
      ansible.builtin.debug:
        msg: "Installed NodeJS version: {{ nodejs_up_to_date.stdout }}"
      when: nodejs_is_installed

    - name: NVM | Show NodeJS latest version
      ansible.builtin.debug:
        msg: "Online NodeJS LTS version: {{ nodejs_latest_version.stdout }}"

    - name: NVM | Detecting Installed nvm
      ansible.builtin.command:
        cmd: which nvm
      changed_when: false
      register: nvm_cmd
      failed_when: false

    - name: NVM | Register nvm status installed
      ansible.builtin.set_fact:
        nvm_is_installed: true
      when: nvm_cmd.stdout|length > 0

    - name: NVM | Register nvm status not installed
      ansible.builtin.set_fact:
        nvm_is_installed: false
      when: nvm_cmd.stdout|length == 0

    - name: NVM | Install latest lts
      ansible.builtin.command: nvm install {{ nodejs_latest_version.stdout }}
      when: nvm_is_installed
      failed_when: false
      changed_when: false
