---
- name: NPM | Check if NodeJS is installed
  ansible.builtin.command: node --version
  register: nodejs_installed
  changed_when: false

- name: NPM | Include NVM role if NodeJS not installed
  ansible.builtin.include_role:
    name: nvm
  tags:
    - nvm
  when: not nodejs_installed

- name: NPM | Detecting Installed npm
  ansible.builtin.command:
    cmd: which npm
  changed_when: false
  register: npm_cmd
  failed_when: false

- name: NPM | Register npm status installed
  ansible.builtin.set_fact:
    npm_is_installed: true
  when: npm_cmd.stdout|length > 0

- name: NPM | Register npm status not installed
  ansible.builtin.set_fact:
    npm_is_installed: false
  when: npm_cmd.stdout|length == 0

- name: NPM | Install NPM Packages
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  with_items:
    - bun
    - blitz
    - lite-server
    - license
    - gitconfig
    - http-server
  when: npm_is_installed
