---
- name: Window Manager | Dependencies
  block:
    - name: Window Manager | i3lock-color
      community.general.pacman:
        executable: yay
        state: present
        name:
          - i3lock-color

    - name: Window Manager | i3, feh, appearance
      ansible.builtin.package:
        name:
          - feh
          - xorg
          - lightdm
          - lightdm-gtk-greeter
          - i3-wm
          - i3status
          - i3blocks
          - dmenu
          - lxappearance
          - terminator
        state: present
      become: true

- name: Window Manager | Start services
  ansible.builtin.service:
    name: lightdm
    enabled: true
    state: started

- name: Window Manager | Config
  block:
    - name: Scripts
      ansible.builtin.template:
        dest: "{{ ansible_user_dir }}/.config/scripts/{{ item }}"
        src: "{{ item }}.j2"
        mode: "0755"
      with_items:
        - lock
        - memory
        - disk

    - name: Config
      ansible.builtin.template:
        dest: "{{ ansible_user_dir }}/.config/i3/config"
        src: config.j2
        mode: "0755"

    - name: Blocks
      ansible.builtin.template:
        dest: "{{ ansible_user_dir }}/.config/i3blocks/i3blocks.conf"
        src: i3blocks.conf.j2
        mode: "0755"
        group: ansible_user_id
        owner: ansible_user_id
