---
- name: Window Manager | Dependencies
  block:
    - name: Remove i3lock
      ansible.builtin.package:
        name:
          - i3lock
        state: absent
      become: true

    - name: Install if not Manjaro
      ansible.builtin.package:
        name:
          - dmenu
          - i3status
        state: present
      when: ansible_lsb.id != "ManjaroLinux"
      become: true

    - name: Window Manager | i3lock-color
      community.general.pacman:
        executable: yay
        state: present
        name:
          - i3lock-color

    - name: Window Manager | i3, feh, appearance
      ansible.builtin.package:
        name:
          - feh
          - xorg
          - lightdm
          - lightdm-gtk-greeter
          - i3-wm
          - i3blocks
          - lxappearance
          - terminator
        state: present
      become: true

- name: Window Manager | Config
  block:
    - name: Scripts Directory
      ansible.builtin.file:
        mode: "0755"
        path: "{{ ansible_user_dir }}/.config/scripts"
        state: directory

    - name: Scripts
      ansible.builtin.template:
        dest: "{{ ansible_user_dir }}/.config/scripts/{{ item }}"
        src: "{{ item }}.j2"
        mode: "0755"
      with_items:
        - lock
        - memory
        - disk

    - name: WM Directory
      ansible.builtin.file:
        mode: "0755"
        path: "{{ ansible_user_dir }}/.config/i3"
        state: directory

    - name: Config
      ansible.builtin.template:
        dest: "{{ ansible_user_dir }}/.config/i3/config"
        src: Archlinux-config.j2
        mode: "0755"

    - name: Blocks Directory
      ansible.builtin.file:
        mode: "0755"
        path: "{{ ansible_user_dir }}/.config/i3blocks"
        state: directory

    - name: Blocks
      ansible.builtin.template:
        dest: "{{ ansible_user_dir }}/.config/i3blocks/i3blocks.conf"
        src: i3blocks.conf.j2
        mode: "0755"
        group: "{{ ansible_user_id }}"
        owner: "{{ ansible_user_id }}"
