---
- name: "Window Manager | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: wm_distribution_config

- name: "Window Manager | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: wm_distribution_config.stat.exists and not ansible_host_environment_is_wsl
