---
- name: "System | {{ ansible_distribution }} | Install formulaes"
  community.general.homebrew:
    name:
      - jq
      - xclip
    state: present

- name: "System | {{ ansible_distribution }} | Install casks"
  community.general.homebrew_cask:
    name:
      - gnu-tar
    state: present
