---
- name: "Karabiner | Install"
  community.general.homebrew_cask:
    name:
      - karabiner-elements
    state: present

- name: "Karabiner | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/karabiner"
    state: directory

- name: "Karabiner | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/karabiner"
    state: link
    force: true
