---
- name: "BRAVE-BROWSER | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: brave_distribution_config

- name: "BRAVE-BROWSER | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: brave_distribution_config.stat.exists and ansible_host_enviroment_is_wsl
