---
- name: Cleanup lazygit downloaded tar
  ansible.builtin.file:
    path: /tmp/{{ lazygit_file }}.tar.gz
    state: absent
  become: true
  when: ansible_distribution == ["Ubuntu", "Archlinux"]

- name: Remove extracted lazygit directory
  ansible.builtin.file:
    path: /tmp/lazygit
    state: absent
  become: true
  when: ansible_distribution == ["Ubuntu", "Archlinux"]
