---
- name: Wezterm | Detecting Installed wezterm
  ansible.builtin.command:
    cmd: which wezterm
  changed_when: false
  register: wezterm_cmd
  failed_when: false

- name: Wezterm | Register wezterm status installed
  ansible.builtin.set_fact:
    wezterm_is_installed: true
  when: wezterm_cmd.stdout|length > 0

- name: Wezterm | Register wezterm status not installed
  ansible.builtin.set_fact:
    wezterm_is_installed: false
  when: wezterm_cmd.stdout|length == 0

- name: Wezterm | Install | {{ ansible_distribution }}
  when: not wezterm_is_installed
  block:
    - name: Wezterm | Add apt_key
      ansible.builtin.apt_key:
        url: https://apt.fury.io/wez/gpg.key
        keyring: /usr/share/keyrings/wezterm-fury.gpg
        state: present
      become: true

    - name: Wezterm | Add repo source
      ansible.builtin.apt_repository:
        repo: |
          deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * * |
          sudo tee /etc/apt/sources.list.d/wezterm.list
        state: present
      become: true

    - name: Wezterm | Installation
      ansible.builtin.apt:
        name:
          - wezterm
        state: present
      become: true
