---
- name: "Starship | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: starship_distribution_config

- name: "Starship | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: starship_distribution_config.stat.exists

- name: "Starship | Check if config files exists"
  stat:
    path: "{{ ansible_user_dir }}/.config/starship/starship.toml"
  register: starship_config_result

- name: "Starship | Remove starship.toml"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/starship"
    state: directory
    recurse: true
    force: true
  when: starship_config_result.stat.exists

- name: "Starship | Create symlink to role files directory"
  ansible.builtin.file:
    src: "starship"
    dest: "{{ ansible_user_dir }}/.config/"
    state: link
    force: true
