---
- name: PHP | Installation
  ansible.builtin.apt:
    name:
      - php
      - libapache2-mod-php
    state: present
  become: true

- name: PHP | Dependencies
  ansible.builtin.apt:
    name:
      - php-cli
      - unzip
    state: present
  become: true

- name: Composer | Detecting Installed composer
  ansible.builtin.command:
    cmd: which composer-browser
  changed_when: false
  register: composer_cmd
  failed_when: false

- name: Composer | Register composer status installed
  ansible.builtin.set_fact:
    composer_is_installed: true
  when: composer_cmd.stdout|length > 0

- name: Composer | Register composer status not installed
  ansible.builtin.set_fact:
    composer_is_installed: false
  when: composer_cmd.stdout|length == 0

- name: PHP | Composer
  when: not composer_is_installed
  block:
    - name: Composer | Download
      ansible.builtin.get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        force: true
        mode: "0755"

    - name: Composer | Execute hash
      ansible.builtin.command: |
        php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH')
        { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      environment:
        HASH: curl -sS https://composer.github.io/installer.sig
      changed_when: false

    - name: Composer | Installation
      ansible.builtin.command: |
        php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      changed_when: false
      become: true
