---
- name: Neovim | Dependencies | {{ ansible_distribution }}
  community.general.pacman:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - fd
      - ripgrep
    state: present
  become: true

- name: Neovim | {{ ansible_distribution }}
  community.general.pacman:
    name:
      - neovim
      - python-pynvim
    state: present
  become: true
