---
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  community.general.pacman:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - fd
      - ripgrep
    state: present
  become: true

- name: "Neovim | {{ ansible_distribution }} | Install Neovim Nightly"
  community.general.pacman:
    name:
      - neovim
      - python-pynvim
    state: present
  become: true
