---
- name: Neovim | Install | {{ ansible_distribution }}
  block:
    - name: Neovim | Detecting Installed nvim
      ansible.builtin.command:
        cmd: which nvim
      changed_when: false
      register: nvim_cmd
      failed_when: false

    - name: Neovim | Register nvim status installed
      ansible.builtin.set_fact:
        nvim_is_installed: true
      when: nvim_cmd.stdout|length > 0

    - name: Neovim | Register nvim status not installed
      ansible.builtin.set_fact:
        nvim_is_installed: false
      when: nvim_cmd.stdout|length == 0

- name: Neovim | Dependencies | {{ ansible_distribution }}
  when: not nvim_is_installed
  block:
    - name: Neovim | Detecting Installed cmake
      ansible.builtin.command:
        cmd: which cmake
      changed_when: false
      register: cmake_cmd
      failed_when: false

    - name: Neovim | Register cmake status installed
      ansible.builtin.set_fact:
        cmake_is_installed: true
      when: cmake_cmd.stdout|length > 0

    - name: Neovim | Register cmake status not installed
      ansible.builtin.set_fact:
        cmake_is_installed: false
      when: cmake_cmd.stdout|length == 0

    - name: Neovim | Install cmake
      ansible.builtin.package:
        name:
          - cmake
        state: present
      when: not cmake_is_installed

    - name: Neovim | Dependencies | Install
      ansible.builtin.package:
        name:
          - curl
          - ansible-lint
          - ripgrep
          - fd
          - ninja
          - gettext
        state: present

- name: Neovim | Check if update needed | {{ ansible_distribution }}
  when: nvim_is_installed
  block:
    - name: Neovim | Download Latest Version JSON
      ansible.builtin.uri:
        url: https://api.github.com/repos/neovim/neovim/releases/tags/nightly
      register: neovim_latest_version_json
      changed_when: false

    - name: Neovim | Registering neovim Latest Release
      ansible.builtin.set_fact:
        neovim_latest_release: "{{ neovim_latest_version_json.json.tag_name }}"

    - name: Neovim | Registering neovim Latest Version
      ansible.builtin.set_fact:
        neovim_latest_version: |
          "{{ neovim_latest_release.stdout | default('') }}"

    - name: Neovim | Getting version information
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          nvim --version | grep -w "NVIM " | awk "NR==1" | tr -d "NVIM "
      args:
        executable: /bin/zsh
      register: current_neovim_version
      changed_when: false
      failed_when: false

    - name: Neovim | Show neovim_latest_release debug
      ansible.builtin.debug:
        var: neovim_latest_release

- name: Neovim | Installation | {{ ansible_distribution }}
  block:
    - name: Neovim | Clone repo
      ansible.builtin.git:
        clone: true
        depth: 1
        repo: https://github.com/neovim/neovim.git
        force: true
        update: true
        dest: "{{ ansible_user_dir }}/neovim"
        version: stable
      register: clone

    - name: Neovim | Build
      community.general.make:
        chdir: "{{ ansible_user_dir }}/neovim"
        params:
          CMAKE_BUILD_TYPE: RelWithDebInfo

    - name: Neovim | Install
      community.general.make:
        chdir: "{{ ansible_user_dir }}/neovim"
        target: install
      become: true

    - name: Remove build folder
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/neovim"
        state: absent
      become: true
