---
- name: Neovim | Dependencies | {{ ansible_distribution }}
  community.general.homebrew:
    name:
      - cmake
      - curl
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
      - fd
    state: present

- name: Neovim | Installation | {{ ansible_distribution }}
  community.general.homebrew:
    name: neovim
    state: present
