---
- name: "Neovim | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: neovim_distribution_config

- name: "Neovim | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: neovim_distribution_config.stat.exists

- name: Neovim | Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Neovim | Create symlink to role files/personal directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/work"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true

- name: Neovim | Create symlink to role files/work directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/work"
    dest: "{{ ansible_user_dir }}/.config/nvim.work"
    state: link
    force: true
