---
- name: Neovim | Dependencies | {{ ansible_distribution }}
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - fd-find
      - ripgrep
    state: present
  become: true

- name: Neovim | Installation | {{ ansible_distribution }}
  ansible.builtin.apt:
    name: neovim
    state: present
  become: true
