#!/usr/bin/env sh

SEPARATOR_LEFT=
SEPARATOR_RIGHT=
TERMINAL_ICON=
CHROME_ICON=
SPOTIFY_ICON=󰓇
DISCORD_ICON=󰙯
KRITA_ICON=
FINDER_ICON=󰀶
WIFI_ICON=
MOBILE_ICON=
BATTERY_ICON_100=󰁹
BATTERY_ICON_70=󰂀
BATTERY_ICON_50=󰁾
BATTERY_ICON_20=󰁻
BATTERY_ICON_10=󰁺
BATTERY_ICON_CHARGING=󰂄
