---
- name: "FONTS | {{ ansible_distribution }} | Git clone nerdfonts"
  ansible.builtin.git:
    repo: "https://github.com/ryanoasis/nerd-fonts.git"
    depth: 1
    dest: "{{ ansible_user_dir }}/.nerd_fonts"

- name: "FONTS | {{ ansible_distribution }} | Install fonts"
  ansible.builtin.command:
    cmd: "/{{ ansible_user_dir }}/.nerd_fonts/install.sh Iosevka, JetBrainsMono"
