---
- name: FONTS | Tap | {{ ansible_distribution }}
  community.general.homebrew_tap:
    name:
      - homebrew/cask-fonts
    state: present

- name: FONTS | Installation | {{ ansible_distribution }}
  community.general.homebrew_cask:
    name:
      - homebrew/cask-fonts/font-jetbrains-mono-nerd-font
      - homebrew/cask-fonts/font-iosevka-nerd-font
    state: latest
